version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: bipa-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1324
      MYSQL_DATABASE: bipa
      TZ: Asia/Seoul
    ports:
      - "3307:3306"     #로컬에 MySQL(3306)이 켜져 있으면 충돌남
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d   # 초기 SQL 자동 실행
      - mysql-data:/var/lib/mysql
    command:
      [
        "--character-set-server=utf8mb4",
        "--collation-server=utf8mb4_unicode_ci"
      ]

volumes:
  mysql-data:
